<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Controllers;


use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;

use Icinga\Module\Enrollment\ActivitylogRestrictor;
use Icinga\Module\Enrollment\Controller;
use Icinga\Module\Enrollment\Forms\ActivitylogForm;
use Icinga\Module\Enrollment\Model\Activitylog;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Enrollment\Common\Database;

use ipl\Stdlib\Filter;
use ipl\Web\Url;


class ActivitylogController extends Controller
{
    /** @var Activitylog The Activitylog object */
    protected $activitylog;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("enrollment/activitylog/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New Activitylog'));

        $values = [];

        $form = (ActivitylogForm::fromId(null))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ActivitylogForm::ON_SUCCESS, function (ActivitylogForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Activitylog successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/activitylogs')
                    );
                } else {
                    Notification::success($this->translate('Updated Activitylog successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/activitylogs')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit Activitylog'));

        $id = $this->params->getRequired('id');

        $query = Activitylog::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));

        $restrictor = new ActivitylogRestrictor();
        $restrictor->applyRestrictions($query);

        $activitylog = $query->first();
        if ($activitylog === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->activitylog = $activitylog;




        $values = $this->activitylog->getValues();




        $form = (ActivitylogForm::fromId($id))->setDb($this->db)
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(ActivitylogForm::ON_SUCCESS, function (ActivitylogForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Activitylog successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/activitylogs')
                    );
                } else {
                    Notification::success($this->translate('Updated Activitylog successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/activitylogs')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }
}
