<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Controllers;

use Icinga\Application\Config;
use Icinga\Module\Enrollment\Forms\BackendConfigForm;
use ipl\Web\Compat\CompatController;


class ConfigController extends CompatController
{
    protected $path;
    public function init()
    {
        $this->assertPermission('config/enrollment');
        parent::init();
    }

    public function backendAction()
    {
        $form = (new BackendConfigForm())
            ->setIniConfig(Config::module('enrollment'));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('backend');
        $this->view->form = $form;
    }
}
