<?php

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Controllers;

use Icinga\Exception\ConfigurationError;

use Icinga\Module\Enrollment\Common\Database;
use Icinga\Module\Enrollment\DashboardDonut;
use Icinga\Module\Enrollment\Model\Userenrollment;
use ipl\Stdlib\Filter;
use ipl\Web\Url;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;

class IndexController extends CompatController
{

    public function indexAction()
    {
        $this->addTitleTab(t('Enrollment Overview'));
        $this->addContent(Html::tag('h1', 'Enrollment Overview'));


        try {
            $conn = Database::get();
        } catch (ConfigurationError $_) {
            $this->render('missing-resource', null, true);
            return;
        }


        $currentTimestamp = time();
        $expired = Userenrollment::on($conn)->filter(Filter::lessThanOrEqual('etime',$currentTimestamp))->filter(Filter::equal('enabled','y'))->count();
        $all = Userenrollment::on($conn)->filter(Filter::equal('enabled','y'))->count();
        $nonExpired = $all - $expired;

        $this->addContent(
            new DashboardDonut(
                (object) [
                    'bad'=>$expired,
                    'good'=>$nonExpired,
                    'title'=>t("User Enrollments"),
                    'labelSmall'=>t('Expired'),
                    'labelUrl'=>Url::fromPath('enrollment/userenrollments',
                        [
                            'enrollment_userenrollment.enabled'=>'y',
                            'enrollment_userenrollment.etime<'=>'now'
                        ]
                    )
                ]
            )
        );



    }

}
