<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Controllers;


use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;

use Icinga\Module\Enrollment\MailHelper;
use Icinga\Module\Enrollment\Model\Userenrollment;
use Icinga\Module\Enrollment\Controller;

use Icinga\Module\Enrollment\Common\Database;

use ipl\Stdlib\Filter;
use ipl\Web\Url;


class SendController extends Controller
{

    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("enrollment/user/send")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }


    public function userAction()
    {

        $this->setTitle($this->translate('Send Mail to a User'));

        $id = $this->params->getRequired('id');

        $query = Userenrollment::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));


        $user = $query->first();
        if ($user === null) {
            throw new NotFoundError(t('Entry not found'));
        }
        MailHelper::sendMail($user);

        $this->redirectHttp(Url::fromPath('enrollment/userenrollments'));


    }

}
