<?php

/* originally from Icinga Web 2 X.509 Module | (c) 2018 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Controllers;


use Icinga\Exception\Http\HttpException;
use Icinga\Exception\NotFoundError;

use Icinga\Module\Enrollment\BackendHelper;
use Icinga\Module\Enrollment\UserenrollmentRestrictor;
use Icinga\Module\Enrollment\Controller;
use Icinga\Module\Enrollment\Forms\UserenrollmentForm;
use Icinga\Module\Enrollment\Model\Userenrollment;
use Icinga\Web\Notification;
use ipl\Html\Form;
use Icinga\Module\Enrollment\Common\Database;

use ipl\Stdlib\Filter;
use ipl\Web\Url;


class UserenrollmentController extends Controller
{

    use BackendHelper;

    /** @var Userenrollment The Userenrollment object */
    protected $userenrollment;
    protected $db;

    public function init()
    {
        if(!$this->Auth()->hasPermission("enrollment/userenrollment/modify")){
            throw new HttpException(401,"Not allowed!");
        }
        $this->db=Database::get();

    }

    public function newAction()
    {

        $this->setTitle($this->translate('New Userenrollment'));

        $values = [];

        $form = (UserenrollmentForm::fromId(null))->setDb($this->db)->setUserBackends($this->loadUserBackends())->setGroupBackends($this->loadUserGroupBackends())
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserenrollmentForm::ON_SUCCESS, function (UserenrollmentForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Userenrollment successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/userenrollments')
                    );
                } else {
                    Notification::success($this->translate('Updated Userenrollment successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/userenrollments')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    public function editAction()
    {

        $this->setTitle($this->translate('Edit Userenrollment'));

        $id = $this->params->getRequired('id');

        $query = Userenrollment::on($this->db)->with([

        ]);
        $query->filter(Filter::equal('id', $id));


        $userenrollment = $query->first();
        if ($userenrollment === null) {
            throw new NotFoundError(t('Entry not found'));
        }

        $this->userenrollment = $userenrollment;




        $values = $this->userenrollment->getValues();




        $form = (UserenrollmentForm::fromId($id))->setDb($this->db)->setUserBackends($this->loadUserBackends())->setGroupBackends($this->loadUserGroupBackends())
            ->setAction((string) Url::fromRequest())->setRenderCreateAndShowButton(false)
            ->populate($values)
            ->on(UserenrollmentForm::ON_SUCCESS, function (UserenrollmentForm $form) {
                $pressedButton = $form->getPressedSubmitElement();
                if ($pressedButton && $pressedButton->getName() === 'remove') {
                    Notification::success($this->translate('Removed Userenrollment successfully'));


                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/userenrollments')
                    );
                } else {
                    Notification::success($this->translate('Updated Userenrollment successfully'));

                    $this->closeModalAndRefreshRemainingViews(
                        Url::fromPath('enrollment/userenrollments')
                    );
                }
            })
            ->handleRequest($this->getServerRequest());

        $this->addContent($form);

    }

    protected function redirectForm(Form $form, $url)
    {
        if (
            $form->hasBeenSubmitted()
            && ((isset($form->valid) && $form->valid === true)
                || $form->isValid())
        ) {
            $this->redirectNow($url);
        }
    }
}
