<?php

/* originally from Icinga Web 2 Reporting Module | (c) 2019 Icinga GmbH | GPLv2 */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Enrollment\Forms;

use Icinga\Module\Enrollment\Common\Database;
use Icinga\Module\Enrollment\Model\Userenrollment;
use Icinga\Util\StringHelper;
use ipl\Html\Contract\FormSubmitElement;
use ipl\Html\HtmlDocument;
use ipl\Sql\Connection;
use ipl\Stdlib\Filter;
use ipl\Web\Compat\CompatForm;

class UserenrollmentForm extends CompatForm
{
    protected $id;
    protected $groupbackends=[];
    protected $userBackendOptions=[];
    protected $groupBackendOptions=[];
    /** @var Connection $db */
    protected $db;
    protected $renderCreateAndShowButton = false;
    protected $submitButtonLabel;

    /**
     * @return mixed
     */
    public function getUserBackends()
    {
        return $this->userBackendOptions;
    }
    /**
     * @param mixed $userBackends
     */
    public function setUserBackends($userBackends)
    {
        $backends=[];
        foreach ($userBackends as $backend){
            if(get_class($backend) === "Icinga\Authentication\User\DbUserBackend"){
                $backends[$backend->getName()]=$backend->getName();
            }
        }
        $this->userBackendOptions=$backends;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getGroupBackends()
    {
        return $this->groupBackendOptions;
    }

    /**
     * @param mixed $groupBackends
     */
    public function setGroupBackends($groupBackends)
    {
        $backends=[];
        foreach ($groupBackends as $backend){
            if(get_class($backend) === "Icinga\Authentication\UserGroup\DbUserGroupBackend"){
                $backends[$backend->getName()]=$backend->getName();
                $this->groupbackends[$backend->getName()]=$backend;
            }
        }
        $this->groupBackendOptions=$backends;
        return $this;
    }


    /**
     * Set whether the create and show submit button should be rendered
     *
     * @param bool $renderCreateAndShowButton
     *
     * @return \Icinga\Module\Enrollment\Forms\UserenrollmentForm
     */
    public function setRenderCreateAndShowButton(bool $renderCreateAndShowButton): self
    {
        $this->renderCreateAndShowButton = $renderCreateAndShowButton;

        return $this;
    }

    /**
     * Create a new form instance with the given user id
     *
     * @param $id
     *
     * @return \Icinga\Module\Enrollment\Forms\UserenrollmentForm
     */
    public static function fromId($id): self
    {
        $form = new static();
        $form->id = $id;

        return $form;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getDb() :Connection
    {
        return $this->db;
    }

    public function setDb($db)
    {
        $this->db = $db;
        return $this;
    }


    public function hasBeenSubmitted(): bool
    {
        return $this->hasBeenSent() && (
                $this->getPopulatedValue('submit')
                || $this->getPopulatedValue('create_show')
                || $this->getPopulatedValue('remove')
            );
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }
    /**
     * Get the label of the submit button
     *
     * @return string
     */
    public function getSubmitButtonLabel(): string
    {
        if ($this->submitButtonLabel !== null) {
            return $this->submitButtonLabel;
        }

        return $this->id === null ? $this->translate('Create User') : $this->translate('Update User');
    }
    protected function assemble()
    {

        $columns = (new Userenrollment())->getColumnDefinitions();

        foreach ($columns as $column=>$options){


            if(is_array($options)){

                $fieldtype = $options['fieldtype']??"text";
                unset($options['fieldtype']);

                if($column === "user_backend"){
                    $options['multiOptions']=$this->getUserBackends();
                }
                if($column === "group_backend"){
                    $options['multiOptions']=$this->getGroupBackends();
                }
                $this->addElement($fieldtype, $column, $options);
            }else{
                $this->addElement('text', $column, [
                    'label' => $options
                ]);
            }
        }
        $this->addElement('submit', 'submit', [
            'label' => $this->getSubmitButtonLabel()
        ]);
        if ($this->id !== null) {
            /** @var FormSubmitElement $removeButton */
            $removeButton = $this->createElement('submit', 'remove', [
                'label'          => $this->translate('Remove User'),
                'class'          => 'btn-remove',
                'formnovalidate' => true
            ]);
            $this->registerElement($removeButton);

            /** @var HtmlDocument $wrapper */
            $wrapper = $this->getElement('submit')->getWrapper();
            $wrapper->prepend($removeButton);


        } elseif ($this->renderCreateAndShowButton) {
            $createAndShow = $this->createElement('submit', 'create_show', [
                'label' => $this->translate('Create and Show'),
            ]);
            $this->registerElement($createAndShow);

            /** @var HtmlDocument $wrapper */
            $wrapper = $this->getElement('submit')->getWrapper();
            $wrapper->prepend($createAndShow);
        }

    }

    public function onSuccess()
    {
        /** @var Connection db */

        $values = $this->getValues();
        $model = new Userenrollment();


        if ($this->id === null) {
            $model->setValues($values);
        } else {
            $model = Userenrollment::on(Database::get())->filter(Filter::equal('id', $this->id))->first();
            if ($this->getPopulatedValue('remove')) {
                $model->delete();
                return;
            }

            $model->setValues($values);
            $model->id=$this->id;


        }
        $groups = StringHelper::trimSplit($model->groups);
        foreach ($groups as $group){
            $backend = $this->groupbackends[$model->group_backend];
            $element = $backend->select()->where('group_name',$group)->fetchRow();
            if($element === false){
                throw new \Exception(sprintf('Group %s not found in backend %s',$group,$model->group_backend));
            }
        }
        $model->save();
    }


}
